server:
  servlet:
    context-path: /card-service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///postgres
    username: postgres
    password: postgres
  cloud:
    gcp:
      project-id: ardent-window-404920
      sql:
        instance-connection-name: ardent-window-404920:us-central1:test-cloud-sql
        database-name: postgres
  jpa:
    hibernate:
      ddl-auto: update